# Generated by Django 2.1.4 on 2019-01-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startX', models.FloatField()),
                ('startY', models.FloatField()),
                ('endX', models.FloatField()),
                ('endY', models.FloatField()),
            ],
        ),
    ]
