# Generated by Django 2.1.4 on 2019-01-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0002_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
    ]
